### ISSUE TITLE
Should we just reuse existing 

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification-pdf-releases#1]
We have https://github.com/bids-standard/bids-schema/tree/main/versions which we are yet to automate (iirc), but may be we should just make it into `bids-standard/releases` repo and have all releases related info (schema, PDFs) in it?

**Comment by sappelhoff** [comment]
This repo exists so that we can have an easy automation of publishing spec PDF files (via Zenodo --> DOI).

If we had a big "releases" repo, we'd have one DOI (per release) for several resources -- I think it would be preferable to have a specific DOI for each specific resource (PDF, schema, html spec, ...)

**Comment by sappelhoff** [comment]
See also:

- https://github.com/bids-standard/bids-specification/issues/1554
- https://github.com/bids-standard/bids-specification/pull/1652
